# Server Configuration
server:
  port: 8081
#  error:
#    include-message: always
#    include-binding-errors: always


# Spring Configuration
spring:
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/demoS?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
